- name: install redis repos
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: yes

- name: enable and install redis
  ansible.builtin.dnf:
    name: "@redis:remi-6.2"
    state: installed

- name: update redis listen address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start redis
  ansible.builtin.systemd:
    state: started
    enabled: true


