- name: update prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: update alerts configuration
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/prometheous/{{ item }}
  loop:
     - service-down-alerts.yml
     - alerts.yml

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheous
    status: restarted








