- name: update prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: update alerts configuration
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/prometheous/{{ item }}
  loop: "{{ alert_files }}"

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheous
    status: restarted

- name: check prometheous is started
  ansible.builtin.shell: netstat -lntp | grep 9090










